azs:
- name: z1

vm_types:
- name: default
  cloud_properties:
    cpu: 2
    disk: 4096
    ram: 2048
- name: concourse-web
  cloud_properties:
    cpu: 2
    disk: 50000
    nested_hardware_virtualization: true
    ram: 8192
- name: concourse-db
  cloud_properties:
    cpu: 4
    disk: 10000
    nested_hardware_virtualization: true
    ram: 8192
- name: concourse-workers
  cloud_properties:
    cpu: 2
    disk: 300000
    nested_hardware_virtualization: true
    ram: 8192

disk_types:
- name: default
  disk_size: 3000
  cloud_properties: { type: thin }
- name: provisioner
  disk_size: 10000
  cloud_properties: { type: thin }
- name: concourse-db
  disk_size: 200000
  cloud_properties: { type: thin }

networks:
- name: concourse 
  subnets:
  - az: z1
    cloud_properties:
      name: VM Network
    dns:
    - 8.8.8.8
    gateway: 192.168.7.1
    range: 192.168.7.0/24
    reserved:
    - 192.168.7.2 - 192.168.7.180
    - 192.168.7.190 - 192.168.7.255
    static:
    - 192.168.7.181 # concourse web
    - 192.168.7.182 # concourse db
 
  type: manual

compilation:
  workers: 5
  reuse_compilation_vms: true
  az: z1
  vm_type: default
  network: concourse
